name: ssgc
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.7+107

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_screenutil: ^5.7.0
  google_fonts: ^6.1.0
  scroll_snap_list: ^0.9.1
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.14
  http: ^1.1.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  lottie: ^2.6.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  syncfusion_flutter_pdfviewer: ^23.1.36
  flutter_windowmanager: ^0.2.0
  image_picker: ^1.0.4
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  open_file: ^3.3.2
  phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3
  otp_autofill: ^3.0.2
  sms_autofill: ^2.3.0
  timer_count_down: ^2.2.2
  telephony: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/animation/
    - assets/pdf/
  uses-material-design: true
